name: Issue Automation

on:
  issues:
    types: [opened]

jobs:
  issue-automation:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write

    steps:
      # 1. 이슈 생성자를 자동으로 Assignee로 할당
      - name: Assign the issue creator
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.actor }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. 프로젝트 자동 할당
      - name: Add to Project
        uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/orgs/YAPP-Github/projects/29
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
